### ISSUE TITLE
[镜像请求] BioArchLinux

### ISSUE THREAD

**Issue by starsareintherose** [isrc-cas/mirror-requests#2]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/isrc-cas/mirror-requests) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/isrc-cas/mirror-requests).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 项目名称与简介 (Project introduction)

Name: BioArchLinux
Introduction: Arch Community for Biologists & Arch Repository for Biological Software
Official web: https://bioarchlinux.org/
Github Repo: https://github.com/BioArchLinux/Packages

### 上游地址与镜像方法 (How to mirror)

```
rsync -rtlivH bioarchlinux.org::sync/ destdir 
```

### 镜像大小 (Mirror size)

30G

**Comment by yinjiayi** [comment]
已经添加。https://mirror.iscas.ac.cn/BioArchLinux/

**Comment by starsareintherose** [comment]
Thanks

**Comment by starsareintherose** [comment]
请问镜像站发生了什么，似乎大部分 repo 都没有了
